version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: install awscli 
          command: |
              sudo apt-get install python-dev && curl -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py --user && export PATH=~/.local/bin:$PATH && pip install --upgrade --user awscli
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build static site
          command: jekyll build
      - deploy:
          name: Publish master to S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export PATH=~/.local/bin:$PATH && aws s3 sync --delete _site/ s3://ledvina-farm/
            fi

